// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"720","screenHeight":"480","changeWindowWidthTo":"720","changeWindowHeightTo":"480","renderingMode":"auto","alwaysDash":"off"}}
];
